import collections.abc
import enum
import numpy
import numpy.typing
import typing
from typing import Callable, ClassVar, overload

ALL_PLAYERS: PrivateInfoType
CHANCE: StateType
DECISION: StateType
DEPTH: SearchLimitType
DUMMY_ROOT_NODE_INFOSTATE: str
ERROR_STATUS: StatusValue
FILLER_INFOSTATE: str
INVALID_ACTION: int
MEAN_FIELD: StateType
MOVETIME: SearchLimitType
NODES: SearchLimitType
NONE: PrivateInfoType
NUM_CHIPS_LOWER_BOUND: int
NUM_CHIPS_UPPER_BOUND: int
NUM_COLORS: int
OK_STATUS: StatusValue
SINGLE_PLAYER: PrivateInfoType
TERMINAL: StateType
UNDEFINED_DECISION_ID: DecisionId
UNDEFINED_LEAF_ID: LeafId
UNDEFINED_SEQUENCE_ID: SequenceId
__version__: str
decision: InfostateNodeType
observation: InfostateNodeType
terminal: InfostateNodeType

class ActionStruct(SpielStruct):
    def __init__(self, *args, **kwargs) -> None: ...

class ActionStructSampler:
    def __init__(self, state, player: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def sample_action_struct(self) -> ActionStruct: ...

class BackgammonState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def augment_with_hit_info(self, player: typing.SupportsInt | typing.SupportsIndex, moves: collections.abc.Sequence[CheckerMove]) -> list[CheckerMove]: ...
    def board(self, player: typing.SupportsInt | typing.SupportsIndex, point: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def checker_moves_to_spiel_move(self, moves: collections.abc.Sequence[CheckerMove]) -> int: ...
    def spiel_move_to_checker_moves(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> list[CheckerMove]: ...
    def translate_action(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex, hit: bool) -> int: ...

class BargainingGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def all_instances(self) -> list[Instance]: ...
    def all_offers(self) -> list[Offer]: ...
    def discount(self) -> float: ...
    def get_instance_index(self, instance: Instance) -> int: ...
    def get_offer_by_quantities(self, quantities: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> tuple[Offer, int]: ...
    def get_offer_index(self, offer: Offer) -> int: ...
    def get_possible_opponent_values(self, player: typing.SupportsInt | typing.SupportsIndex, pool: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], values: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[list[int]]: ...
    def max_turns(self) -> int: ...
    def prob_end(self) -> float: ...

class BargainingState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def agree_action(self) -> int: ...
    def instance(self) -> Instance: ...
    def offers(self) -> list[Offer]: ...
    def set_instance(self, instance: Instance) -> None: ...

class BatchedTrajectory:
    actions: list[list[int]]
    batch_size: int
    legal_actions: list[list[list[int]]]
    max_trajectory_length: int
    next_is_terminal: list[list[int]]
    observations: list[list[list[float]]]
    player_ids: list[list[int]]
    player_policies: list[list[list[float]]]
    rewards: list[list[float]]
    state_indices: list[list[int]]
    valid: list[list[int]]
    def __init__(self, batch_size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def resize_fields(self, max_trajectory_length: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class Board:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, size: typing.SupportsInt | typing.SupportsIndex, num_players: typing.SupportsInt | typing.SupportsIndex, num_colors: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def apply_trade(self, position: tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsInt | typing.SupportsIndex], trade: Trade) -> None: ...
    def clone(self) -> Board: ...
    def in_bounds(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> bool: ...
    def pretty_board_string(self) -> str: ...
    def to_string(self) -> str: ...
    @property
    def board(self) -> list[int]: ...
    @property
    def chips(self) -> list[list[int]]: ...
    @property
    def num_chips(self) -> list[int]: ...
    @property
    def num_colors(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    @property
    def positions(self) -> list[int]: ...
    @property
    def size(self) -> int: ...

class Bot:
    def __init__(self) -> None: ...
    def clone(self) -> Bot: ...
    def force_action(self, state: State, action: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def get_policy(self, state: State) -> list[tuple[int, float]]: ...
    def inform_action(self, state: State, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def inform_actions(self, state: State, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def is_clonable(self) -> bool: ...
    def provides_force_action(self) -> bool: ...
    def provides_policy(self) -> bool: ...
    def restart(self) -> None: ...
    def restart_at(self, state: State) -> None: ...
    def step(self, state: State) -> int: ...
    def step_verbose(self, state: State) -> tuple[int, str]: ...
    def step_with_policy(self, state: State) -> tuple[list[tuple[int, float]], int]: ...

class BridgeGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def contract_string(self, contract_index: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    @overload
    def new_initial_state(self) -> State: ...
    @overload
    def new_initial_state(self, tournament_seed: typing.SupportsInt | typing.SupportsIndex, board_number: typing.SupportsInt | typing.SupportsIndex) -> State: ...
    def num_possible_contracts(self) -> int: ...
    def private_observation_tensor_size(self) -> int: ...
    def public_observation_tensor_size(self) -> int: ...

class BridgeState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def contract_index(self) -> int: ...
    def current_phase(self) -> int: ...
    def possible_contracts(self, *args, **kwargs): ...
    def private_observation_tensor(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[float]: ...
    def public_observation_tensor(self) -> list[float]: ...
    def score_by_contract(self, *args, **kwargs): ...
    def score_for_contracts(self, player: typing.SupportsInt | typing.SupportsIndex, contracts: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[int]: ...
    def write_observation_tensor(self, observation_tensor: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...

class CFRBRSolver:
    def __init__(self, game: Game) -> None: ...
    def average_policy(self) -> Policy: ...
    def current_policy(self) -> Policy: ...
    def evaluate_and_update_policy(self) -> None: ...

class CFRPlusSolver:
    def __init__(self, game: Game) -> None: ...
    def average_policy(self) -> Policy: ...
    def current_policy(self) -> Policy: ...
    def evaluate_and_update_policy(self) -> None: ...
    def tabular_average_policy(self) -> TabularPolicy: ...

class CFRSolver:
    def __init__(self, game: Game) -> None: ...
    def average_policy(self) -> Policy: ...
    def current_policy(self) -> Policy: ...
    def evaluate_and_update_policy(self) -> None: ...
    def tabular_average_policy(self) -> TabularPolicy: ...
    def tabular_current_policy(self) -> TabularPolicy: ...

class CatchGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def num_columns(self) -> int: ...
    def num_rows(self) -> int: ...

class CatchState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def ball_col(self) -> int: ...
    def ball_row(self) -> int: ...
    def paddle_col(self) -> int: ...

class CheckerMove:
    hit: bool
    num: int
    pos: int
    def __init__(self, *args, **kwargs) -> None: ...

class ChessGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def is_chess960(self) -> bool: ...

class ChessState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def board(self) -> chess.ChessBoard: ...
    def debug_string(self) -> str: ...
    def is_repetition_draw(self) -> bool: ...
    def moves_history(self) -> list[chess.Move]: ...
    def num_repetitions(self, state: ChessState) -> int: ...
    def parse_move_to_action(self, move_str: str) -> int: ...
    def start_fen(self) -> str: ...

class ChildSelectionPolicy:
    __members__: ClassVar[dict] = ...  # read-only
    PUCT: ClassVar[ChildSelectionPolicy] = ...
    UCT: ClassVar[ChildSelectionPolicy] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class ColoredTrailsGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def lookup_trade(self, trade_index: typing.SupportsInt | typing.SupportsIndex) -> Trade: ...
    def pass_action(self) -> int: ...
    def responder_trade_with_player_action(self, player: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def sample_random_board_completion(self, player: typing.SupportsInt | typing.SupportsIndex, board: Board, seed: typing.SupportsInt | typing.SupportsIndex) -> tuple[Board, int]: ...

class ColoredTrailsState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_board(self) -> Board: ...
    def get_proposals(self) -> list[Trade]: ...
    def set_chips_and_trade_proposals(self, player: typing.SupportsInt | typing.SupportsIndex, chips: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], trade: Trade, proposals: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...

class CorrDevBuilder:
    def __init__(self, seed: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def add_deterministic_joint_policy(self, policy: TabularPolicy, weight: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def add_mixed_joint_policy(self, policy: TabularPolicy, weight: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def add_sampled_joint_policy(self, policy: TabularPolicy, num_samples: typing.SupportsInt | typing.SupportsIndex, weight: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def get_correlation_device(self) -> list[tuple[float, TabularPolicy]]: ...

class CorrDistInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def best_response_policies(self) -> list[TabularPolicy]: ...
    @property
    def best_response_values(self) -> list[float]: ...
    @property
    def conditional_best_response_policies(self) -> list[list[TabularPolicy]]: ...
    @property
    def deviation_incentives(self) -> list[float]: ...
    @property
    def dist_value(self) -> float: ...
    @property
    def on_policy_values(self) -> list[float]: ...

class CrazyhouseGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def is_chess960(self) -> bool: ...

class CrazyhouseState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def board(self) -> crazyhouse.CrazyhouseBoard: ...
    def debug_string(self) -> str: ...
    def in_check(self) -> bool: ...
    def is_repetition_draw(self) -> bool: ...
    def moves_history(self) -> list[crazyhouse.Move]: ...
    def num_repetitions(self, state: CrazyhouseState) -> int: ...
    def parse_move_to_action(self, move_str: str) -> int: ...
    def start_fen(self) -> str: ...

class CrosswordGame(Game):
    ActionStruct: ClassVar[type[crossword.CrosswordActionStruct]] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def crossword_file(self, puzzle_index: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def num_puzzles(self) -> int: ...
    def num_words(self) -> int: ...

class CrosswordState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def board(self) -> crossword.CrosswordBoard: ...
    def clue_solved(self) -> list[int]: ...

class DecisionId:
    def __init__(self, id_value: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def id(self) -> int: ...
    def is_undefined(self) -> bool: ...
    def next(self) -> None: ...
    def __copy__(self) -> DecisionId: ...
    def __deepcopy__(self) -> DecisionId: ...
    def __eq__(self, other: DecisionId) -> bool: ...
    def __ne__(self, other: DecisionId) -> bool: ...

class DecisionIdRange:
    def __init__(self, start: typing.SupportsInt | typing.SupportsIndex, end: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def __iter__(self): ...

class DecisionVector:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[object]) -> None: ...
    def __copy__(self) -> DecisionVector: ...
    def __deepcopy__(self) -> DecisionVector: ...
    def __getitem__(self, id) -> object: ...
    def __len__(self) -> int: ...

class DecisionVectorFloat:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...
    def __copy__(self) -> DecisionVectorFloat: ...
    def __deepcopy__(self) -> DecisionVectorFloat: ...
    def __getitem__(self, id) -> float: ...
    def __len__(self) -> int: ...

class DotsAndBoxesState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def dbn_string(self) -> str: ...

class EuchreGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...

class Evaluator:
    def __init__(self, *args, **kwargs) -> None: ...

class ExternalSamplingMCCFRSolver:
    def __init__(self, game: Game, seed: typing.SupportsInt | typing.SupportsIndex = ..., avg_type: MCCFRAverageType = ...) -> None: ...
    def average_policy(self) -> Policy: ...
    def run_iteration(self) -> None: ...

class ForbiddenError(RuntimeError): ...

class Game:
    def __init__(self, game_type: GameType, game_info: GameInfo, parameters: collections.abc.Mapping[str, GameParameter]) -> None: ...
    def action_struct_spec(self) -> tuple[str, str]: ...
    def action_to_string(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def deserialize_state(self, serialized_data: str) -> State: ...
    def get_parameters(self) -> dict[str, GameParameter]: ...
    def get_type(self) -> GameType: ...
    def information_state_tensor_layout(self) -> TensorLayout: ...
    def information_state_tensor_shape(self) -> list[int]: ...
    def information_state_tensor_size(self) -> int: ...
    def make_observer(self, *args, **kwargs): ...
    def max_chance_nodes_in_history(self) -> int: ...
    def max_chance_outcomes(self) -> int: ...
    def max_game_length(self) -> int: ...
    def max_history_length(self) -> int: ...
    def max_move_number(self) -> int: ...
    def max_utility(self) -> float: ...
    def min_utility(self) -> float: ...
    @overload
    def new_initial_state(self) -> State: ...
    @overload
    def new_initial_state(self, state: str) -> State: ...
    @overload
    def new_initial_state(self, state: json) -> State: ...
    @overload
    def new_initial_state(self, state: StateStruct) -> State: ...
    def new_initial_state_for_population(self, population: typing.SupportsInt | typing.SupportsIndex) -> State: ...
    def new_initial_states(self) -> list[State]: ...
    def num_distinct_actions(self) -> int: ...
    def num_players(self) -> int: ...
    def observation_tensor_layout(self) -> TensorLayout: ...
    def observation_tensor_shape(self) -> list[int]: ...
    def observation_tensor_size(self) -> int: ...
    def policy_tensor_shape(self) -> list[int]: ...
    def serialize(self) -> str: ...
    def to_string(self) -> str: ...
    def utility_sum(self) -> float | None: ...
    def __eq__(self, other: Game) -> bool: ...

class GameInfo:
    @overload
    def __init__(self, num_distinct_actions: typing.SupportsInt | typing.SupportsIndex, max_chance_outcomes: typing.SupportsInt | typing.SupportsIndex, num_players: typing.SupportsInt | typing.SupportsIndex, min_utility: typing.SupportsFloat | typing.SupportsIndex, max_utility: typing.SupportsFloat | typing.SupportsIndex, utility_sum: typing.SupportsFloat | typing.SupportsIndex | None = ..., max_game_length: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, game_info: GameInfo) -> None: ...
    @property
    def max_chance_outcomes(self) -> int: ...
    @property
    def max_game_length(self) -> int: ...
    @property
    def max_utility(self) -> float: ...
    @property
    def min_utility(self) -> float: ...
    @property
    def num_distinct_actions(self) -> int: ...
    @property
    def num_players(self) -> int: ...
    @property
    def utility_sum(self) -> float | None: ...

class GameParametersStruct(SpielStruct):
    game_name: str
    def __init__(self, *args, **kwargs) -> None: ...

class GameType:
    class ChanceMode:
        __members__: ClassVar[dict] = ...  # read-only
        DETERMINISTIC: ClassVar[GameType.ChanceMode] = ...
        EXPLICIT_STOCHASTIC: ClassVar[GameType.ChanceMode] = ...
        SAMPLED_STOCHASTIC: ClassVar[GameType.ChanceMode] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    class Dynamics:
        __members__: ClassVar[dict] = ...  # read-only
        MEAN_FIELD: ClassVar[GameType.Dynamics] = ...
        SEQUENTIAL: ClassVar[GameType.Dynamics] = ...
        SIMULTANEOUS: ClassVar[GameType.Dynamics] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    class Information:
        __members__: ClassVar[dict] = ...  # read-only
        IMPERFECT_INFORMATION: ClassVar[GameType.Information] = ...
        ONE_SHOT: ClassVar[GameType.Information] = ...
        PERFECT_INFORMATION: ClassVar[GameType.Information] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    class RewardModel:
        __members__: ClassVar[dict] = ...  # read-only
        REWARDS: ClassVar[GameType.RewardModel] = ...
        TERMINAL: ClassVar[GameType.RewardModel] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...

    class Utility:
        __members__: ClassVar[dict] = ...  # read-only
        CONSTANT_SUM: ClassVar[GameType.Utility] = ...
        GENERAL_SUM: ClassVar[GameType.Utility] = ...
        IDENTICAL: ClassVar[GameType.Utility] = ...
        ZERO_SUM: ClassVar[GameType.Utility] = ...
        __entries: ClassVar[dict] = ...
        def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
        def __eq__(self, other: object) -> bool: ...
        def __hash__(self) -> int: ...
        def __index__(self) -> int: ...
        def __int__(self) -> int: ...
        def __ne__(self, other: object) -> bool: ...
        @property
        def name(self) -> str: ...
        @property
        def value(self) -> int: ...
    @overload
    def __init__(self, short_name: str, long_name: str, dynamics, chance_mode, information, utility, reward_model, max_num_players: typing.SupportsInt | typing.SupportsIndex, min_num_players: typing.SupportsInt | typing.SupportsIndex, provides_information_state_string: bool, provides_information_state_tensor: bool, provides_observation_string: bool, provides_observation_tensor: bool, parameter_specification: collections.abc.Mapping[str, GameParameter] = ..., default_loadable: bool = ..., provides_factored_observation_string: bool = ..., action_structs_only: bool = ...) -> None: ...
    @overload
    def __init__(self, game_type: GameType) -> None: ...
    def pretty_print(self) -> str: ...
    def __eq__(self, other: GameType) -> bool: ...
    @property
    def action_structs_only(self) -> bool: ...
    @property
    def chance_mode(self): ...
    @property
    def default_loadable(self) -> bool: ...
    @property
    def dynamics(self): ...
    @property
    def information(self): ...
    @property
    def is_concrete(self) -> bool: ...
    @property
    def long_name(self) -> str: ...
    @property
    def max_num_players(self) -> int: ...
    @property
    def min_num_players(self) -> int: ...
    @property
    def parameter_specification(self) -> dict[str, GameParameter]: ...
    @property
    def provides_factored_observation_string(self) -> bool: ...
    @property
    def provides_information_state_string(self) -> bool: ...
    @property
    def provides_information_state_tensor(self) -> bool: ...
    @property
    def provides_observation_string(self) -> bool: ...
    @property
    def provides_observation_tensor(self) -> bool: ...
    @property
    def reward_model(self): ...
    @property
    def short_name(self) -> str: ...
    @property
    def utility(self): ...

class GinRummyGame(Game):
    ObservationStruct: ClassVar[type[gin_rummy.GinRummyObservationStruct]] = ...
    StateStruct: ClassVar[type[gin_rummy.GinRummyStateStruct]] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def knock_card(self) -> int: ...
    def oklahoma(self) -> bool: ...

class GoFishGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def ask_after_empty_draw(self) -> bool: ...
    def ask_string_to_action(self, ask_str: str) -> int: ...
    def end_on_first_out(self) -> bool: ...
    def fish_string_to_action(self, fish_str: str) -> int: ...
    def initial_cards(self) -> int: ...
    def most_books_wins(self) -> bool: ...
    def new_specific_state(self, state_str: str) -> State: ...
    def ranks(self) -> int: ...
    def suits(self) -> int: ...

class GoFishState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def booked(self) -> list[int]: ...
    def drawn_since_was_asked(self) -> list[list[int]]: ...
    def phase(self) -> go_fish.Phase: ...
    def player_books(self) -> list[int]: ...
    def player_cards(self) -> list[list[int]]: ...
    def player_counts(self, rank: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    def player_did_ask(self) -> list[list[int]]: ...
    def player_min(self) -> list[list[int]]: ...
    def player_was_asked(self) -> list[list[bool]]: ...
    def pool(self) -> list[int]: ...
    def pool_size(self) -> int: ...

class GomokuGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def action_to_move(self, action: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    def anti(self) -> bool: ...
    def connect(self) -> int: ...
    def dims(self) -> int: ...
    def move_to_action(self, coord: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> int: ...
    def size(self) -> int: ...
    def wrap(self) -> bool: ...

class GomokuState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_symmetry_policy(self, *args, **kwargs): ...
    def hash_value(self) -> int: ...
    def set_symmetry_policy(self, policy) -> None: ...
    def symmetric_hash(self) -> int: ...
    def winning_line(self) -> list[list[int]]: ...

class Header:
    game_string: str
    meta_data: str
    returns: list[float]
    terminal: bool
    def __init__(self) -> None: ...

class HeartsGame(Game):
    ObservationStruct: ClassVar[type[hearts.HeartsObservationStruct]] = ...
    StateStruct: ClassVar[type[hearts.HeartsStateStruct]] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class IIGObservationType:
    def __init__(self, public_info: bool = ..., perfect_recall: bool, private_info: PrivateInfoType = ...) -> None: ...
    @property
    def perfect_recall(self) -> bool: ...
    @property
    def private_info(self) -> PrivateInfoType: ...
    @property
    def public_info(self) -> bool: ...

class ISMCTSBot(Bot):
    def __init__(self, seed: typing.SupportsInt | typing.SupportsIndex, evaluator: Evaluator, uct_c: typing.SupportsFloat | typing.SupportsIndex, max_simulations: typing.SupportsInt | typing.SupportsIndex, max_world_samples: typing.SupportsInt | typing.SupportsIndex = ..., final_policy_type: ISMCTSFinalPolicyType = ..., use_observation_string: bool = ..., allow_inconsistent_action_sets: bool = ..., max_wall_clock_time: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def get_policy(self, state: State) -> list[tuple[int, float]]: ...
    def provides_policy(self) -> bool: ...
    def restart(self) -> None: ...
    def restart_at(self, state: State) -> None: ...
    def step(self, state: State) -> int: ...
    def step_with_policy(self, state: State) -> tuple[list[tuple[int, float]], int]: ...

class ISMCTSFinalPolicyType:
    __members__: ClassVar[dict] = ...  # read-only
    MAX_VALUE: ClassVar[ISMCTSFinalPolicyType] = ...
    MAX_VISIT_COUNT: ClassVar[ISMCTSFinalPolicyType] = ...
    NORMALIZED_VISIT_COUNT: ClassVar[ISMCTSFinalPolicyType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InfostateNode:
    def __init__(self, *args, **kwargs) -> None: ...
    def address_str(self) -> str: ...
    def all_sequence_ids(self, *args, **kwargs): ...
    def child_at(self, index: typing.SupportsInt | typing.SupportsIndex) -> InfostateNode: ...
    def corresponding_chance_reach_probs(self) -> list[float]: ...
    def corresponding_states(self) -> list[State]: ...
    def corresponding_states_size(self) -> int: ...
    def decision_id(self, *args, **kwargs): ...
    def depth(self) -> int: ...
    def end_sequence_id(self, *args, **kwargs): ...
    def has_infostate_string(self) -> bool: ...
    def incoming_index(self) -> int: ...
    def infostate_string(self) -> str: ...
    def is_filler_node(self) -> bool: ...
    def is_leaf_node(self) -> bool: ...
    def is_root_node(self) -> bool: ...
    def legal_actions(self) -> list[int]: ...
    def make_certificate(self) -> str: ...
    def num_children(self) -> int: ...
    def parent(self) -> object: ...
    def sequence_id(self, *args, **kwargs): ...
    def start_sequence_id(self, *args, **kwargs): ...
    def terminal_chance_reach_prob(self) -> float: ...
    def terminal_history(self) -> list[int]: ...
    def terminal_utility(self) -> float: ...
    def tree(self, *args, **kwargs): ...
    def type(self, *args, **kwargs): ...
    def __copy__(self) -> None: ...
    def __deepcopy__(self, memo: dict) -> None: ...
    def __eq__(self, other: InfostateNode) -> bool: ...
    def __hash__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[InfostateNode]: ...
    def __ne__(self, other: InfostateNode) -> bool: ...

class InfostateNodeType:
    __members__: ClassVar[dict] = ...  # read-only
    __entries: ClassVar[dict] = ...
    decision: ClassVar[InfostateNodeType] = ...
    observation: ClassVar[InfostateNodeType] = ...
    terminal: ClassVar[InfostateNodeType] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class InfostateNodeVector:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, nodes: collections.abc.Sequence[InfostateNode]) -> None: ...
    @overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def append(self, x: InfostateNode) -> None: ...
    def clear(self) -> None: ...
    @overload
    def extend(self, L: collections.abc.Sequence[InfostateNode]) -> None: ...
    @overload
    def extend(self, L: collections.abc.Iterable) -> None: ...
    def insert(self, i: typing.SupportsInt | typing.SupportsIndex, x: InfostateNode) -> None: ...
    @overload
    def pop(self) -> InfostateNode: ...
    @overload
    def pop(self, i: typing.SupportsInt | typing.SupportsIndex) -> InfostateNode: ...
    def __bool__(self) -> bool: ...
    @overload
    def __delitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def __delitem__(self, s: slice) -> None: ...
    @overload
    def __getitem__(self, s: slice) -> list[InfostateNode]: ...
    @overload
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> InfostateNode: ...
    def __iter__(self) -> collections.abc.Iterator[InfostateNode]: ...
    def __len__(self) -> int: ...
    @overload
    def __setitem__(self, index: typing.SupportsInt | typing.SupportsIndex, value: InfostateNode) -> None: ...
    @overload
    def __setitem__(self, s: slice, value: collections.abc.Sequence[InfostateNode]) -> None: ...

class InfostateNodeVector2D:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, nodes: collections.abc.Sequence[collections.abc.Sequence[InfostateNode]]) -> None: ...
    @overload
    def __init__(self, iterable: collections.abc.Iterable) -> None: ...
    def append(self, x: collections.abc.Sequence[InfostateNode]) -> None: ...
    def clear(self) -> None: ...
    @overload
    def extend(self, L: collections.abc.Sequence[collections.abc.Sequence[InfostateNode]]) -> None: ...
    @overload
    def extend(self, L: collections.abc.Iterable) -> None: ...
    def insert(self, i: typing.SupportsInt | typing.SupportsIndex, x: collections.abc.Sequence[InfostateNode]) -> None: ...
    @overload
    def pop(self) -> list[InfostateNode]: ...
    @overload
    def pop(self, i: typing.SupportsInt | typing.SupportsIndex) -> list[InfostateNode]: ...
    def __bool__(self) -> bool: ...
    @overload
    def __delitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @overload
    def __delitem__(self, s: slice) -> None: ...
    @overload
    def __getitem__(self, s: slice) -> list[list[InfostateNode]]: ...
    @overload
    def __getitem__(self, index: typing.SupportsInt | typing.SupportsIndex) -> list[InfostateNode]: ...
    def __iter__(self) -> collections.abc.Iterator[list[InfostateNode]]: ...
    def __len__(self) -> int: ...
    @overload
    def __setitem__(self, index: typing.SupportsInt | typing.SupportsIndex, value: collections.abc.Sequence[InfostateNode]) -> None: ...
    @overload
    def __setitem__(self, s: slice, value: collections.abc.Sequence[collections.abc.Sequence[InfostateNode]]) -> None: ...

class InfostateTree:
    def __init__(self, *args, **kwargs) -> None: ...
    def acting_player(self) -> int: ...
    def all_decision_ids(self) -> DecisionIdRange: ...
    def all_decision_infostates(self) -> list: ...
    def all_sequence_ids(self) -> SequenceIdRange: ...
    def best_response(self, gradient: TreeplexVectorFloat) -> tuple[float, TreeplexVectorFloat]: ...
    def best_response_value(self, gradient: LeafVectorFloat) -> float: ...
    def decision_for_sequence(self, sequence_id: SequenceId) -> object: ...
    def decision_id_for_sequence(self, sequence_id: SequenceId) -> DecisionId | None: ...
    def decision_id_from_infostate_string(self, infostate_string: str) -> DecisionId: ...
    def decision_ids_with_parent_seq(self, sequence_id: SequenceId) -> list[DecisionId]: ...
    def decision_infostate(self, decision_id: DecisionId) -> InfostateNode: ...
    def empty_sequence(self) -> SequenceId: ...
    def is_leaf_sequence(self, sequence_id: SequenceId) -> bool: ...
    def leaf_node(self, leaf_id: LeafId) -> InfostateNode: ...
    def leaf_nodes(self) -> list: ...
    def nodes_at_depth(self, depth: typing.SupportsInt | typing.SupportsIndex) -> list: ...
    def nodes_at_depths(self) -> list: ...
    def num_decisions(self) -> int: ...
    def num_leaves(self) -> int: ...
    def num_sequences(self) -> int: ...
    def observation_infostate(self, sequence_id: SequenceId) -> InfostateNode: ...
    def root(self) -> InfostateNode: ...
    def root_branching_factor(self) -> int: ...
    def stores_all_world_states(self) -> bool: ...
    def tree_height(self) -> int: ...
    def __copy__(self) -> None: ...
    def __deepcopy__(self) -> None: ...

class Instance:
    pool: list[int]
    values: list[list[int]]
    def __init__(self) -> None: ...

class LeafId:
    def __init__(self, id_value: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def id(self) -> int: ...
    def is_undefined(self) -> bool: ...
    def next(self) -> None: ...
    def __copy__(self) -> LeafId: ...
    def __deepcopy__(self) -> LeafId: ...
    def __eq__(self, other: LeafId) -> bool: ...
    def __ne__(self, other: LeafId) -> bool: ...

class LeafIdRange:
    def __init__(self, start: typing.SupportsInt | typing.SupportsIndex, end: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def __iter__(self): ...

class LeafVector:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[object]) -> None: ...
    def __copy__(self) -> LeafVector: ...
    def __deepcopy__(self) -> LeafVector: ...
    def __getitem__(self, id) -> object: ...
    def __len__(self) -> int: ...

class LeafVectorFloat:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...
    def __copy__(self) -> LeafVectorFloat: ...
    def __deepcopy__(self) -> LeafVectorFloat: ...
    def __getitem__(self, id) -> float: ...
    def __len__(self) -> int: ...

class MCCFRAverageType:
    __members__: ClassVar[dict] = ...  # read-only
    FULL: ClassVar[MCCFRAverageType] = ...
    SIMPLE: ClassVar[MCCFRAverageType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class MCTSBot(Bot):
    def __init__(self, game: Game, evaluator: Evaluator, uct_c: typing.SupportsFloat | typing.SupportsIndex, max_simulations: typing.SupportsInt | typing.SupportsIndex, max_memory_mb: typing.SupportsInt | typing.SupportsIndex, solve: bool, seed: typing.SupportsInt | typing.SupportsIndex, verbose: bool, child_selection_policy: ChildSelectionPolicy = ..., max_wall_clock_time: typing.SupportsFloat | typing.SupportsIndex = ...) -> None: ...
    def mcts_search(self, state: State) -> SearchNode: ...
    def step(self, state: State) -> int: ...

class MatrixGame(NormalFormGame):
    @overload
    def __init__(self, game_type: GameType, parameters: collections.abc.Mapping[str, GameParameter], row_action_names: collections.abc.Sequence[str], col_action_names: collections.abc.Sequence[str], row_utilities: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex], col_utilities: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...
    @overload
    def __init__(self, game_type: GameType, parameters: collections.abc.Mapping[str, GameParameter], row_action_names: collections.abc.Sequence[str], col_action_names: collections.abc.Sequence[str], row_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], col_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None: ...
    def col_action_name(self, col: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def col_utilities(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def col_utility(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def num_cols(self) -> int: ...
    def num_rows(self) -> int: ...
    def player_utilities(self, player: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float64]: ...
    def player_utility(self, player: typing.SupportsInt | typing.SupportsIndex, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def row_action_name(self, row: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def row_utilities(self) -> numpy.typing.NDArray[numpy.float64]: ...
    def row_utility(self, row: typing.SupportsInt | typing.SupportsIndex, col: typing.SupportsInt | typing.SupportsIndex) -> float: ...

class NegotiationState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def agent_utils(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    def item_pool(self) -> list[int]: ...

class NormalFormGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_utilities(self, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[float]: ...
    def get_utility(self, player: typing.SupportsInt | typing.SupportsIndex, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> float: ...

class ObservationStruct(SpielStruct):
    def __init__(self, *args, **kwargs) -> None: ...

class Observer:
    def __init__(self, *args, **kwargs) -> None: ...

class Offer:
    quantities: list[int]
    def __init__(self) -> None: ...

class OutcomeSamplingMCCFRSolver:
    def __init__(self, game: Game, epsilon: typing.SupportsFloat | typing.SupportsIndex = ..., seed: typing.SupportsInt | typing.SupportsIndex = ...) -> None: ...
    def average_policy(self) -> Policy: ...
    def run_iteration(self) -> None: ...

class PartialTabularPolicy(Policy):
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> None: ...
    @overload
    def __init__(self, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]], default_policy: Policy) -> None: ...
    @overload
    def get_state_policy(self, state: State) -> list[tuple[int, float]]: ...
    @overload
    def get_state_policy(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> list[tuple[int, float]]: ...
    @overload
    def get_state_policy(self, info_state: str) -> list[tuple[int, float]]: ...
    def policy_table(self) -> dict[str, list[tuple[int, float]]]: ...
    def set_prob(self, info_state: str, action: typing.SupportsInt | typing.SupportsIndex, prob: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def set_state_policy(self, info_state: str, policy: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]) -> None: ...

class PlayerAction:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def action(self) -> int: ...
    @property
    def player(self) -> int: ...

class PlayerId(enum.IntEnum):
    __new__: ClassVar[Callable] = ...
    CHANCE: ClassVar[PlayerId] = ...
    DEFAULT_PLAYER_ID: ClassVar[PlayerId] = ...
    INVALID: ClassVar[PlayerId] = ...
    MEAN_FIELD: ClassVar[PlayerId] = ...
    SIMULTANEOUS: ClassVar[PlayerId] = ...
    TERMINAL: ClassVar[PlayerId] = ...
    _generate_next_value_: ClassVar[Callable] = ...
    _member_map_: ClassVar[dict] = ...
    _member_names_: ClassVar[list] = ...
    _member_type_: ClassVar[type[int]] = ...
    _unhashable_values_: ClassVar[list] = ...
    _use_args_: ClassVar[bool] = ...
    _value2member_map_: ClassVar[dict] = ...
    def __format__(self, *args, **kwargs) -> str: ...

class Policy:
    def __init__(self) -> None: ...
    @overload
    def action_probabilities(self, state: State) -> dict[int, float]: ...
    @overload
    def action_probabilities(self, info_state: str) -> dict[int, float]: ...
    @overload
    def get_state_policy(self, state: State) -> list[tuple[int, float]]: ...
    @overload
    def get_state_policy(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> list[tuple[int, float]]: ...
    @overload
    def get_state_policy(self, info_state: str) -> list[tuple[int, float]]: ...
    @overload
    def get_state_policy_as_parallel_vectors(self, state: State) -> tuple[list[int], list[float]]: ...
    @overload
    def get_state_policy_as_parallel_vectors(self, info_state: str) -> tuple[list[int], list[float]]: ...
    def serialize(self, double_precision: typing.SupportsInt | typing.SupportsIndex = ..., delimiter: str = ...) -> str: ...

class PreferredActionPolicy(Policy):
    def __init__(self, preferred_actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def get_state_policy(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> list[tuple[int, float]]: ...

class PrivateInfoType:
    __members__: ClassVar[dict] = ...  # read-only
    ALL_PLAYERS: ClassVar[PrivateInfoType] = ...
    NONE: ClassVar[PrivateInfoType] = ...
    SINGLE_PLAYER: ClassVar[PrivateInfoType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class RandomRolloutEvaluator(Evaluator):
    def __init__(self, n_rollouts: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> None: ...

class SearchLimitType:
    __members__: ClassVar[dict] = ...  # read-only
    DEPTH: ClassVar[SearchLimitType] = ...
    MOVETIME: ClassVar[SearchLimitType] = ...
    NODES: ClassVar[SearchLimitType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class SearchNode:
    def __init__(self, *args, **kwargs) -> None: ...
    def best_child(self) -> SearchNode: ...
    def children_str(self, state: State) -> str: ...
    def to_string(self, state: State) -> str: ...
    @property
    def action(self) -> int: ...
    @property
    def children(self) -> list[SearchNode]: ...
    @property
    def explore_count(self) -> int: ...
    @property
    def outcome(self) -> list[float]: ...
    @property
    def player(self) -> int: ...
    @property
    def prior(self) -> float: ...
    @property
    def total_reward(self) -> float: ...

class SequenceId:
    def __init__(self, id_value: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def id(self) -> int: ...
    def is_undefined(self) -> bool: ...
    def next(self) -> None: ...
    def __copy__(self) -> SequenceId: ...
    def __deepcopy__(self) -> SequenceId: ...
    def __eq__(self, other: SequenceId) -> bool: ...
    def __ne__(self, other: SequenceId) -> bool: ...

class SequenceIdRange:
    def __init__(self, start: typing.SupportsInt | typing.SupportsIndex, end: typing.SupportsInt | typing.SupportsIndex, tree) -> None: ...
    def __iter__(self): ...

class SgfNode:
    def __init__(self) -> None: ...
    @property
    def children(self) -> list[SgfNode]: ...
    @property
    def properties(self) -> list[SgfProperty]: ...

class SgfProperty:
    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def values(self) -> list[str]: ...

class ShogiGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...

class ShogiState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def board(self) -> shogi.ShogiBoard: ...
    def debug_string(self) -> str: ...
    def in_check(self) -> bool: ...
    def is_repetition_end(self) -> bool: ...
    def moves_history(self) -> list[shogi.Move]: ...
    def num_repetitions(self, state: ShogiState) -> int: ...
    def parse_move_to_action(self, move_str: str) -> int: ...
    def start_sfen(self) -> str: ...

class SpadesGame(Game):
    def __init__(self, *args, **kwargs) -> None: ...
    def contract_string(self, contract_index: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def num_possible_contracts(self) -> int: ...
    def private_observation_tensor_size(self) -> int: ...
    def public_observation_tensor_size(self) -> int: ...

class SpadesState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def contract_indexes(self, *args, **kwargs): ...
    def current_phase(self) -> int: ...
    def get_current_scores(self, *args, **kwargs): ...
    def is_game_over(self) -> bool: ...
    def possible_contracts(self, *args, **kwargs): ...
    def private_observation_tensor(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[float]: ...
    def public_observation_tensor(self) -> list[float]: ...
    def set_current_player(self, player: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def set_current_scores(self, scores) -> None: ...
    def write_observation_tensor(self, observation_tensor: typing.Annotated[numpy.typing.ArrayLike, numpy.float32]) -> None: ...

class SpanTensor:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def data(self) -> numpy.typing.NDArray[numpy.float32]: ...
    @property
    def name(self) -> str: ...
    @property
    def shape(self) -> list[int]: ...

class SpanTensorInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def shape(self) -> list[int]: ...

class SpielError(RuntimeError): ...

class SpielStruct:
    def __init__(self, *args, **kwargs) -> None: ...
    def to_dict(self) -> json: ...
    def to_json(self) -> str: ...

class State:
    def __init__(self, state) -> None: ...
    def action_to_string(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    @overload
    def action_to_struct(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> ActionStruct: ...
    @overload
    def action_to_struct(self, action: typing.SupportsInt | typing.SupportsIndex) -> ActionStruct: ...
    @overload
    def actions_to_struct(self, player: typing.SupportsInt | typing.SupportsIndex, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> ActionStruct: ...
    @overload
    def actions_to_struct(self, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> ActionStruct: ...
    def apply_action(self, action: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def apply_action_struct(self, action: ActionStruct) -> Status: ...
    def apply_action_with_legality_check(self, action: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def apply_actions(self, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def apply_actions_with_legality_checks(self, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def chance_outcomes(self) -> list[tuple[int, float]]: ...
    def child(self, action: typing.SupportsInt | typing.SupportsIndex) -> State: ...
    def clone(self) -> State: ...
    def current_player(self) -> int: ...
    def distribution_support(self) -> list[str]: ...
    def full_history(self) -> list[PlayerAction]: ...
    def get_action_struct_sampler(self, player: typing.SupportsInt | typing.SupportsIndex) -> ActionStructSampler: ...
    def get_game(self, *args, **kwargs): ...
    def get_type(self) -> StateType: ...
    def history(self) -> list[int]: ...
    def history_str(self) -> str: ...
    @overload
    def information_state_string(self, player: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    @overload
    def information_state_string(self) -> str: ...
    @overload
    def information_state_tensor(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[float]: ...
    @overload
    def information_state_tensor(self) -> list[float]: ...
    def is_chance_node(self) -> bool: ...
    def is_initial_non_chance_state(self) -> bool: ...
    def is_initial_state(self) -> bool: ...
    def is_mean_field_node(self) -> bool: ...
    def is_player_node(self) -> bool: ...
    def is_simultaneous_node(self) -> bool: ...
    def is_terminal(self) -> bool: ...
    @overload
    def legal_actions(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    @overload
    def legal_actions(self) -> list[int]: ...
    @overload
    def legal_actions_mask(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    @overload
    def legal_actions_mask(self) -> list[int]: ...
    def mean_field_population(self) -> int: ...
    def move_number(self) -> int: ...
    def num_distinct_actions(self) -> int: ...
    def num_players(self) -> int: ...
    @overload
    def observation_string(self, player: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    @overload
    def observation_string(self) -> str: ...
    @overload
    def observation_tensor(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[float]: ...
    @overload
    def observation_tensor(self) -> list[float]: ...
    def player_return(self, player: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def player_reward(self, player: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    def resample_from_infostate(self, player_id: typing.SupportsInt | typing.SupportsIndex, rng: collections.abc.Callable[[], typing.SupportsFloat | typing.SupportsIndex]) -> State: ...
    def returns(self) -> list[float]: ...
    def rewards(self) -> list[float]: ...
    def serialize(self) -> str: ...
    def starting_state(self) -> State: ...
    def starting_state_str(self) -> str: ...
    @overload
    def string_to_action(self, player: typing.SupportsInt | typing.SupportsIndex, action_str: str) -> int: ...
    @overload
    def string_to_action(self, action_str: str) -> int: ...
    def struct_to_actions(self, action_struct: ActionStruct) -> list[int]: ...
    def to_dict(self) -> json: ...
    def to_json(self) -> str: ...
    @overload
    def to_observation_struct(self, player: typing.SupportsInt | typing.SupportsIndex) -> ObservationStruct: ...
    @overload
    def to_observation_struct(self) -> ObservationStruct: ...
    def to_string(self) -> str: ...
    def to_struct(self) -> StateStruct: ...
    def undo_action(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def update_distribution(self, distribution: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...
    def validate_action_struct(self, action_struct: ActionStruct) -> Status: ...

class StateStruct(SpielStruct):
    def __init__(self, *args, **kwargs) -> None: ...

class StateType:
    __members__: ClassVar[dict] = ...  # read-only
    CHANCE: ClassVar[StateType] = ...
    DECISION: ClassVar[StateType] = ...
    MEAN_FIELD: ClassVar[StateType] = ...
    TERMINAL: ClassVar[StateType] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class Status:
    def __init__(self, status_value: StatusValue, message: str) -> None: ...
    def message(self) -> str: ...
    def ok(self) -> bool: ...
    def to_string(self) -> str: ...

class StatusValue:
    __members__: ClassVar[dict] = ...  # read-only
    ERROR_STATUS: ClassVar[StatusValue] = ...
    OK_STATUS: ClassVar[StatusValue] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class StatusWithSgfNodes:
    def __init__(self, status_value: StatusValue, message: str, nodes) -> None: ...
    def message(self) -> str: ...
    def ok(self) -> bool: ...
    def to_string(self) -> str: ...
    def value(self, *args, **kwargs): ...

class SymmetryPolicy:
    allow_reflection_rotations: bool
    allow_reflections: bool
    def __init__(self) -> None: ...

class TabularBestResponse:
    @overload
    def __init__(self, game: Game, player: typing.SupportsInt | typing.SupportsIndex, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> None: ...
    @overload
    def __init__(self, game: Game, player: typing.SupportsInt | typing.SupportsIndex, policy: Policy) -> None: ...
    @overload
    def __init__(self, game: Game, player: typing.SupportsInt | typing.SupportsIndex, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]], prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex, action_value_tolerance: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, game: Game, player: typing.SupportsInt | typing.SupportsIndex, policy: Policy, prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex, action_value_tolerance: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def get_best_response_actions(self) -> dict[str, int]: ...
    def get_best_response_policy(self, *args, **kwargs): ...
    @overload
    def set_policy(self, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> None: ...
    @overload
    def set_policy(self, policy: Policy) -> None: ...
    def value(self, info_state: str) -> float: ...
    def value_from_state(self, state: State) -> float: ...

class TabularBestResponseMDP:
    def __init__(self, game: Game, policy: Policy) -> None: ...
    def compute_best_response(self, max_player: typing.SupportsInt | typing.SupportsIndex) -> TabularBestResponseMDPInfo: ...
    def compute_best_responses(self) -> TabularBestResponseMDPInfo: ...
    def exploitability(self) -> TabularBestResponseMDPInfo: ...
    def nash_conv(self) -> TabularBestResponseMDPInfo: ...

class TabularBestResponseMDPInfo:
    def __init__(self, *args, **kwargs) -> None: ...
    @property
    def br_policies(self) -> list[TabularPolicy]: ...
    @property
    def br_values(self) -> list[float]: ...
    @property
    def deviation_incentives(self) -> list[float]: ...
    @property
    def exploitability(self) -> float: ...
    @property
    def nash_conv(self) -> float: ...
    @property
    def on_policy_values(self) -> list[float]: ...

class TabularPolicy(Policy):
    def __init__(self, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> None: ...
    def get_state_policy(self, info_state: str) -> list[tuple[int, float]]: ...
    def policy_table(self) -> dict[str, list[tuple[int, float]]]: ...
    def size(self) -> int: ...
    def to_string(self) -> str: ...
    def __len__(self) -> int: ...

class TarokContract:
    __members__: ClassVar[dict] = ...  # read-only
    BEGGAR: ClassVar[TarokContract] = ...
    COLOUR_VALAT_WITHOUT: ClassVar[TarokContract] = ...
    KLOP: ClassVar[TarokContract] = ...
    NOT_SELECTED: ClassVar[TarokContract] = ...
    ONE: ClassVar[TarokContract] = ...
    OPEN_BEGGAR: ClassVar[TarokContract] = ...
    SOLO_ONE: ClassVar[TarokContract] = ...
    SOLO_THREE: ClassVar[TarokContract] = ...
    SOLO_TWO: ClassVar[TarokContract] = ...
    SOLO_WITHOUT: ClassVar[TarokContract] = ...
    THREE: ClassVar[TarokContract] = ...
    TWO: ClassVar[TarokContract] = ...
    VALAT_WITHOUT: ClassVar[TarokContract] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TarokGamePhase:
    __members__: ClassVar[dict] = ...  # read-only
    BIDDING: ClassVar[TarokGamePhase] = ...
    CARD_DEALING: ClassVar[TarokGamePhase] = ...
    FINISHED: ClassVar[TarokGamePhase] = ...
    KING_CALLING: ClassVar[TarokGamePhase] = ...
    TALON_EXCHANGE: ClassVar[TarokGamePhase] = ...
    TRICKS_PLAYING: ClassVar[TarokGamePhase] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TarokState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def captured_mond_penalties(self) -> list[int]: ...
    def card_action_to_string(self, action: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def current_game_phase(self, *args, **kwargs): ...
    def player_cards(self, player: typing.SupportsInt | typing.SupportsIndex) -> list[int]: ...
    def scores_without_captured_mond_penalties(self) -> list[int]: ...
    def selected_contract(self, *args, **kwargs): ...
    def talon(self) -> list[int]: ...
    def talon_sets(self) -> list[list[int]]: ...
    def trick_cards(self) -> list[int]: ...

class TensorGame(NormalFormGame):
    def __init__(self, game_type: GameType, parameters: collections.abc.Mapping[str, GameParameter], action_names: collections.abc.Sequence[collections.abc.Sequence[str]], utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> None: ...
    def action_name(self, player: typing.SupportsInt | typing.SupportsIndex, action: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def as_matrix_game(self) -> MatrixGame: ...
    def player_utilities(self, player: typing.SupportsInt | typing.SupportsIndex) -> numpy.typing.NDArray[numpy.float64]: ...
    def player_utility(self, player: typing.SupportsInt | typing.SupportsIndex, actions: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> float: ...
    def shape(self) -> list[int]: ...

class TensorLayout:
    __members__: ClassVar[dict] = ...  # read-only
    CHW: ClassVar[TensorLayout] = ...
    HWC: ClassVar[TensorLayout] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class TinyBridgeAuctionState(State):
    def __init__(self, *args, **kwargs) -> None: ...

class TinyBridgePlayState(State):
    def __init__(self, *args, **kwargs) -> None: ...

class Trade:
    giving: list[int]
    receiving: list[int]
    def __init__(self, giving: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], receiving: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    def to_string(self) -> str: ...

class TradeCommState(State):
    def __init__(self, *args, **kwargs) -> None: ...

class Trajectory:
    @overload
    def __init__(self, trajectory_str: str) -> None: ...
    @overload
    def __init__(self, trajectory_json: json) -> None: ...
    @overload
    def __init__(self, state: State) -> None: ...
    def header(self) -> Header: ...
    def reconstruct_all_states(self) -> list[State]: ...
    def reconstruct_final_state(self) -> State: ...
    def to_string(self) -> str: ...
    def transitions(self) -> list[Transition]: ...

class TrajectoryRecorder:
    def __init__(self, game: Game, params: collections.abc.Mapping[str, typing.SupportsInt | typing.SupportsIndex], batch_size: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def record_batch(self, policies: collections.abc.Sequence[TabularPolicy], num_episodes: typing.SupportsInt | typing.SupportsIndex, max_steps: typing.SupportsInt | typing.SupportsIndex) -> BatchedTrajectory: ...

class Transition:
    action: int
    player: int
    def __init__(self) -> None: ...
    def get_chance_outcomes(self) -> list[tuple[int, float]]: ...
    def get_joint_action(self) -> list[int]: ...
    def get_legal_actions(self) -> list[int]: ...

class TreeplexVector:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[object]) -> None: ...
    def __copy__(self) -> TreeplexVector: ...
    def __deepcopy__(self) -> TreeplexVector: ...
    def __getitem__(self, id) -> object: ...
    def __len__(self) -> int: ...

class TreeplexVectorFloat:
    @overload
    def __init__(self, tree) -> None: ...
    @overload
    def __init__(self, tree, vec: collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]) -> None: ...
    def __copy__(self) -> TreeplexVectorFloat: ...
    def __deepcopy__(self) -> TreeplexVectorFloat: ...
    def __getitem__(self, id) -> float: ...
    def __len__(self) -> int: ...

class TurnBasedSimultaneousState(State):
    def __init__(self, *args, **kwargs) -> None: ...
    def simultaneous_game_state(self) -> State: ...

class UniformPolicy(Policy):
    def __init__(self) -> None: ...
    def get_state_policy(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> list[tuple[int, float]]: ...

class UniformProbabilitySampler:
    @overload
    def __init__(self, min_value: typing.SupportsFloat | typing.SupportsIndex, max_value: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @overload
    def __init__(self, seed: typing.SupportsInt | typing.SupportsIndex, min_value: typing.SupportsFloat | typing.SupportsIndex, max_value: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    def __call__(self) -> float: ...

class _Observation:
    def __init__(self, game: Game, observer: Observer) -> None: ...
    def compress(self) -> bytes: ...
    def decompress(self, data: str) -> None: ...
    def has_string(self) -> bool: ...
    def has_tensor(self) -> bool: ...
    def set_from(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    def string_from(self, state: State, player: typing.SupportsInt | typing.SupportsIndex) -> str: ...
    def tensors(self) -> list[SpanTensor]: ...
    def tensors_info(self) -> list[SpanTensorInfo]: ...

def GetFlatDirichletPolicy(game: Game, seed: typing.SupportsInt | typing.SupportsIndex, player: typing.SupportsInt | typing.SupportsIndex = ...) -> TabularPolicy: ...
def GetRandomDeterministicPolicy(game: Game, seed: typing.SupportsInt | typing.SupportsIndex, player: typing.SupportsInt | typing.SupportsIndex = ...) -> TabularPolicy: ...
def GetRandomDeterministicVisitPolicy(game: Game, seed: typing.SupportsInt | typing.SupportsIndex, player: typing.SupportsInt | typing.SupportsIndex = ...) -> TabularPolicy: ...
def GetRandomPolicy(game: Game, seed: typing.SupportsInt | typing.SupportsIndex, player: typing.SupportsInt | typing.SupportsIndex = ...) -> TabularPolicy: ...
def UniformRandomPolicy(game: Game) -> TabularPolicy: ...
@overload
def bots_that_can_play_game(game: Game, player: typing.SupportsInt | typing.SupportsIndex) -> list[str]: ...
@overload
def bots_that_can_play_game(game: Game) -> list[str]: ...
def build_state_from_history_string(game_string: str, history_string: str, max_steps: typing.SupportsInt | typing.SupportsIndex = ...) -> tuple[Game, State]: ...
@overload
def cce_dist(game: Game, correlation_device: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, TabularPolicy]], player: typing.SupportsInt | typing.SupportsIndex, prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex = ..., action_value_tolerance: typing.SupportsFloat | typing.SupportsIndex = ...) -> CorrDistInfo: ...
@overload
def cce_dist(game: Game, correlation_device: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, TabularPolicy]], prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex = ..., action_value_tolerance: typing.SupportsFloat | typing.SupportsIndex = ...) -> CorrDistInfo: ...
def ce_dist(game: Game, correlation_device: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, TabularPolicy]], action_value_tolerance: typing.SupportsFloat | typing.SupportsIndex = ...) -> CorrDistInfo: ...
def combo_to_string(combo: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> str: ...
def convert_to_cached_tree(game: Game) -> Game: ...
def convert_to_turn_based(game: Game) -> Game: ...
@overload
def create_matrix_game(row_player_name: str, col_player_name: str, row_action_names: collections.abc.Sequence[str], col_action_names: collections.abc.Sequence[str], row_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], col_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> MatrixGame: ...
@overload
def create_matrix_game(row_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], col_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> MatrixGame: ...
@overload
def create_matrix_game(row_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], col_utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> MatrixGame: ...
@overload
def create_repeated_game(stage_game: Game, parameters: collections.abc.Mapping[str, GameParameter]) -> Game: ...
@overload
def create_repeated_game(stage_game_string: str, parameters: collections.abc.Mapping[str, GameParameter]) -> Game: ...
@overload
def create_tensor_game(game_name: str, game_description: str, action_names: collections.abc.Sequence[collections.abc.Sequence[str]], utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]]) -> TensorGame: ...
@overload
def create_tensor_game(utilities: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsFloat | typing.SupportsIndex]], shape: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> TensorGame: ...
@overload
def create_tensor_game(utilities: collections.abc.Sequence[typing.Annotated[numpy.typing.ArrayLike, numpy.float64]]) -> TensorGame: ...
def deserialize_game(serialized_data: str) -> Game: ...
def deserialize_game_and_state(serialized_data: str) -> tuple[Game, State]: ...
def determinize_corr_dev(correlation_device: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, TabularPolicy]]) -> list[tuple[float, TabularPolicy]]: ...
def error_status(message: str) -> Status: ...
def evaluate_bots(state: State, bots: collections.abc.Sequence[Bot], seed: typing.SupportsInt | typing.SupportsIndex) -> list[float]: ...
@overload
def expected_returns(state: State, policies: collections.abc.Sequence[Policy], depth_limit: typing.SupportsInt | typing.SupportsIndex, use_infostate_get_policy: bool, prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex = ...) -> list[float]: ...
@overload
def expected_returns(state: State, joint_policy: Policy, depth_limit: typing.SupportsInt | typing.SupportsIndex, use_infostate_get_policy: bool, prob_cut_threshold: typing.SupportsFloat | typing.SupportsIndex = ...) -> list[float]: ...
@overload
def expected_returns_of_deterministic_policies_from_seeds(state: State, policy_seeds: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> list[float]: ...
@overload
def expected_returns_of_deterministic_policies_from_seeds(state: State, policy_seeds: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], policies: collections.abc.Sequence[Policy]) -> list[float]: ...
@overload
def exploitability(game: Game, policy: Policy) -> float: ...
@overload
def exploitability(game: Game, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> float: ...
def extensive_to_matrix_game(game: Game) -> MatrixGame: ...
def extensive_to_tensor_game(game: Game) -> TensorGame: ...
def game_parameters_from_string(params_string: str) -> dict[str, GameParameter]: ...
def game_parameters_to_string(parameters: collections.abc.Mapping[str, GameParameter]) -> str: ...
def game_to_nfg_string(game: Game) -> str: ...
def get_kuhn_poker_efg_data() -> str: ...
def get_sample_efg_data() -> str: ...
def hulh_game_string(acpc_game_string: str) -> str: ...
def hunl_game_string(acpc_game_string: str) -> str: ...
def is_bot_registered(bot_name: str) -> bool: ...
def is_valid_sf_strategy(strategy: TreeplexVectorFloat) -> bool: ...
@overload
def load_bot(bot_name: str, game: Game, player: typing.SupportsInt | typing.SupportsIndex) -> Bot: ...
@overload
def load_bot(bot_name: str, game: Game, player: typing.SupportsInt | typing.SupportsIndex, params: collections.abc.Mapping[str, GameParameter]) -> Bot: ...
def load_efg_game(efg_string: str) -> Game: ...
@overload
def load_game(game_string: str) -> Game: ...
@overload
def load_game(game_string: str, parameters: collections.abc.Mapping[str, GameParameter]) -> Game: ...
@overload
def load_game(params_struct: GameParametersStruct) -> Game: ...
@overload
def load_game_as_cached_tree(game_string: str) -> Game: ...
@overload
def load_game_as_cached_tree(game_string: str, parameters: collections.abc.Mapping[str, GameParameter]) -> Game: ...
@overload
def load_game_as_turn_based(game_string: str) -> Game: ...
@overload
def load_game_as_turn_based(game_string: str, parameters: collections.abc.Mapping[str, GameParameter]) -> Game: ...
def load_game_from_json(json_str: str) -> Game: ...
def load_games(multi_game_string: str, separator: str = ...) -> list[Game]: ...
def load_matrix_game(game_string: str) -> MatrixGame: ...
def load_nfg_game(nfg_string: str) -> Game: ...
def load_tensor_game(game_string: str) -> TensorGame: ...
def make_policy_bot(game: Game, player: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex, policy) -> Bot: ...
def make_simple_gin_rummy_bot(params: collections.abc.Mapping[str, GameParameter], player_id: typing.SupportsInt | typing.SupportsIndex) -> Bot: ...
def make_stateful_random_bot(game: Game, player: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> Bot: ...
def make_uniform_random_bot(player: typing.SupportsInt | typing.SupportsIndex, seed: typing.SupportsInt | typing.SupportsIndex) -> Bot: ...
@overload
def nash_conv(game: Game, policy: Policy, use_state_get_policy: bool = ...) -> float: ...
@overload
def nash_conv(game: Game, policy_table: collections.abc.Mapping[str, collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]]]) -> float: ...
def num_deterministic_policies(game: Game, player: typing.SupportsInt | typing.SupportsIndex) -> int: ...
def ok_status() -> Status: ...
def random_sim_test(game: Game, num_sims: typing.SupportsInt | typing.SupportsIndex, serialize: bool, verbose: bool, mask_test: bool = ..., state_checker_fn: collections.abc.Callable[[State], None] = ..., mean_field_population: typing.SupportsInt | typing.SupportsIndex = ..., observer=..., specific_initial_state: State = ...) -> None: ...
def random_sim_test_with_specific_initial_state(game: Game, num_sims: typing.SupportsInt | typing.SupportsIndex, specific_initial_state: State, serialize: bool = ...) -> None: ...
def read_contents_from_file(filename: str, mode: str) -> str: ...
def read_sgf_string(sgf_string: str) -> StatusWithSgfNodes: ...
def record_batched_trajectories(game: Game, policies: collections.abc.Sequence[TabularPolicy], params: collections.abc.Mapping[str, typing.SupportsInt | typing.SupportsIndex], batch_size: typing.SupportsInt | typing.SupportsIndex, include_observations: bool, num_episodes: typing.SupportsInt | typing.SupportsIndex, max_steps: typing.SupportsInt | typing.SupportsIndex) -> BatchedTrajectory: ...
def register_game(game_type: GameType, creator: collections.abc.Callable) -> None: ...
def registered_bots() -> list[str]: ...
def registered_concrete_games() -> list[GameType]: ...
def registered_concrete_names() -> list[str]: ...
def registered_games() -> list[GameType]: ...
def registered_names() -> list[str]: ...
def sample_action(outcomes: collections.abc.Sequence[tuple[typing.SupportsInt | typing.SupportsIndex, typing.SupportsFloat | typing.SupportsIndex]], rng_value: typing.SupportsFloat | typing.SupportsIndex) -> tuple[int, float]: ...
def sampled_determinize_corr_dev(correlation_device: collections.abc.Sequence[tuple[typing.SupportsFloat | typing.SupportsIndex, TabularPolicy]], num_samples: typing.SupportsInt | typing.SupportsIndex) -> list[tuple[float, TabularPolicy]]: ...
def score(player: typing.SupportsInt | typing.SupportsIndex, board: Board) -> tuple[int, bool]: ...
def serialize_game_and_state(game: Game, state: State) -> str: ...
def to_joint_tabular_policy(policies: collections.abc.Sequence[TabularPolicy], include_empty: bool) -> TabularPolicy: ...
def turn_based_goofspiel_game_string(num_cards: typing.SupportsInt | typing.SupportsIndex) -> str: ...
def uniform_correlation_device(policies: collections.abc.Sequence[TabularPolicy]) -> list[tuple[float, TabularPolicy]]: ...
def write_contents_to_file(filename: str, mode: str, contents: str) -> None: ...
